<a href="https://colab.research.google.com/github/mmilannaik/bostonhousepricing/blob/main/W5S1_Task_13_NumPy_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Note: In Data Science googling is a very important skill. If you find some difficulties to solve the problem, google it and try to find some clues to solve.**

In [1]:
import numpy as np

###`Q-1` Create a null vector of size 10 but the fifth value which is 1.



In [ ]:
#Code here
a = np.zeros(10)
a[4]=1
a


array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

###`Q-2` Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) and print the array and avg of the array.

In [ ]:
#Code here
a = input('Enter the first number')
b = input('Enter second number')

arr = np.array(np.random.rand(int(a)*int(b)))
print(arr)
arr = arr.reshape(int(a),int(b))
print('average of array is ',np.mean(arr))

Enter the first number3
Enter second number4
[0.97744824 0.89704476 0.68335866 0.70130334 0.52903591 0.19871355
 0.65462934 0.04107067 0.80773805 0.4568603  0.50574121 0.27988376]
average of array is  0.5610689828007865


3###`Q-3`Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.

Eg.-
```
[[1,1,1,1],
[1,0,0,1],
[1,0,0,1],
[1,1,1,1]]
```

In [ ]:
arr = np.zeros((4,4))
arr[0,:]=1
arr[-1,:]=1
arr[:,0]=1
arr[:,-1]=1

In [ ]:
#Code here
def array_f(a,b):
  arr = np.zeros((int(a),int(b)))
  arr[0,:]=1
  arr[-1,:]=1
  arr[:,0]=1
  arr[:,-1]=1
  return arr

In [ ]:
array_f(5,6)

array([[1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1.]])

###`Q-4` Create a vector of size 10 with values ranging from 0 to 1, both excluded.


In [ ]:
#Code here
np.arange(0.05,1,0.05)

array([0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 , 0.55,
       0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

###`Q-5` Can you create a identity mattrix of shape (3,4). If yes write code for it.

In [ ]:
#Code here
s = (3,4)
np.ones(s)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

###`Q-6:` Create a 5x5 matrix with row values ranging from 0 to 4.

In [ ]:
#Code here
arr = np.zeros((5,5))
#np.random.random((5,5))
arr = arr + np.arange(5)
arr

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

###`Q-7:`  Consider a random integer (in range 1 to 100) vector with shape `(10,2)` representing coordinates, and coordinates of a point as array is given. Create an array of distance of each point in the random vectros from the given point. Distance array should be interger type.

```
point = np.array([2,3])
```


In [ ]:
#code here
ran_arr = np.random.randint(1,101,size=(10,2))
point = np.array([2,3])
dist = np.sqrt(np.sum((ran_arr-point)**2,axis=1))
dist

array([28.0713377 , 46.06517123, 34.98571137, 56.63920903, 88.48163651,
       78.23681998, 67.26812024, 26.01922366, 67.89698079, 60.6052803 ])

###`Q-8:` Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [ ]:
#Code here
# for 100th element
linear_index = 99
z = 99%8
y = (99//8)%7
x = 99// (7*8)
print(x,y,z)

1 5 3


In [ ]:
99//8

12

### `Q-9:` Arrays

You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type float.



**Input Format:**

A single line of input containing space separated numbers.

**Output Format:**

Print the reverse NumPy array with type float.

**Example 1:**

Input:

```bash
1 2 3 4 -8 -10
```

Output:

```bash
[-10.  -8.   4.   3.   2.   1.]
```

In [ ]:
#Code here
arr = [1,2,3,4,5]
out = []
for i in np.flip(arr):
  out.append(float(i))
out

[5.0, 4.0, 3.0, 2.0, 1.0]

### `Q-10:` Elements count

Count the number of elements of a numpy array.



**Example 1:**

Input:
```bash
np.array([])
```

Output:
```bash
elements_count :  0
```

**Example 2:**

Input:
```bash
np.array([1, 2])
```

Output:
```bash
elements_count :  2
```

In [ ]:
#Code here
input = [2,3,4]
print('elements_count :',len(input))

elements_count : 3


### `Q-11:` Softmax function

Create a Python function to calculate the Softmax of the given numpy 1D array. The function only accepts the numpy 1D array, otherwise raise error.

$$\Large \sigma(\vec z)_i = \frac{e^{z_i}}{\sum_{j=i}^{K}{e^{z_j}}}$$

https://en.wikipedia.org/wiki/Softmax_function



**Example 1:**

Input:
```bash
[86.03331084 37.7285648  48.64908087 87.16563062 38.40852563 37.20006318]
```

Output:
```bash
[2.43733249e-01, 2.56112115e-22, 1.41628284e-17, 7.56266751e-01,
       5.05514197e-22, 1.50974911e-22]
```

**Example 2:**

Input:
```bash
[33.17344305 45.61961654 82.05405781 80.9647098  68.82830233 91.52064278]
```

Output:
```bash
[4.57181035e-26, 1.16249923e-20, 7.73872596e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01]
```

In [ ]:
#Code here
import numpy as np
import math
input_string = input()
input_list = [float(num)for num in input_string.split()]
denom = [math.exp(i) for i in input_list]
output_list = []
for i in input_list:
  temp = (math.exp(i))/sum(denom)
  output_list.append(temp)


1 2


In [ ]:
output_list

[0.2689414213699951, 0.7310585786300049]

### `Q-12:` Vertical stack

Write a python function that accepts infinite number of numpy arrays and do the vertical stack to them. Then return that new array as result. The function only accepts the numpy array, otherwise raise error.



**Example 1:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]
```

Output:

```bash
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
```

**Example 2:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]

c= [[0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

Output:
```bash
[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

In [ ]:
#Coder here
def vertical_st(*args):
  return [isinstance(arg,np.ndarray) for arg in args]
  new_arr = np.vstack(args)
  return new_arr

In [ ]:
array2 = np.array([[1, 2], [3, 4]])
not_array = [1, 2, 3]
vertical_st(array2,not_array)

[True, False]

### `Q-13:` Dates

Create a python function named **date_array** that accepts two dates as string format and returns a numpy array of dates between those 2 dates. The function only accept 2 strings, otherwise raise error. The date format should be like this only: `2022-12-6`. The end date should be included and for simplicity, choose dates from a same year.



**Example 1:**

Input:
```bash
date_array(start = '2020-09-15', end = '2020-09-25')
```

Output:
```bash
['2020-09-15', '2020-09-16', '2020-09-17', '2020-09-18',
 '2020-09-19', '2020-09-20', '2020-09-21', '2020-09-22',
 '2020-09-23', '2020-09-24', '2020-09-25']
```

**Example 2:**

Input:
```bash
date_array(start = '2022-12-01', end = '2022-12-06')
```

Output:
```bash
['2022-12-01', '2022-12-02', '2022-12-03', '2022-12-04', '2022-12-05', '2022-12-06']
```

**Example 3:**

Input:
```bash
date_array(start = '2020-11-25', end = '2020-11-30')
```

Output:
```bash
['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
 '2020-11-29', '2020-11-30']
```

In [ ]:
#Code here
def date_array(start,end):
  date_range = np.arange(start,end,dtype='datetime64[D]')
  return date_range

In [ ]:
# check test case
date_array(start = '2022-12-01', end = '2022-12-06')


date_array(start = '2020-11-25', end = '2020-11-30')

array(['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
       '2020-11-29'], dtype='datetime64[D]')

###`Q-14:` Subtract the mean of each row from a matrix.

In [ ]:
#code here
mat = np.random.rand(3,4)
mat

array([[0.30792959, 0.32420442, 0.9129625 , 0.40866218],
       [0.45651365, 0.88363668, 0.77751824, 0.28040124],
       [0.57162108, 0.73419198, 0.14677893, 0.8812713 ]])

In [ ]:
mat2 = mat - np.reshape(mat.mean(axis=1),(3,1))

In [ ]:
mat2

array([[-0.18051008, -0.16423525,  0.42452283, -0.07977749],
       [-0.1430038 ,  0.28411923,  0.17800079, -0.31911622],
       [-0.01184474,  0.15072615, -0.43668689,  0.29780548]])

###`Q-15:` Swap column-1 of array with column-2 in the array.

In [ ]:
#Code here
mat_sw = np.random.rand(3,4)

In [ ]:
mat_sw

array([[0.61222483, 0.38573067, 0.64746328, 0.30783724],
       [0.8196928 , 0.52315853, 0.57379612, 0.30507082],
       [0.23724769, 0.90080798, 0.69429896, 0.08561021]])

In [ ]:
mat_sw[:,[0,1]] = mat_sw[:,[1,0]]
mat_sw

array([[0.38573067, 0.61222483, 0.64746328, 0.30783724],
       [0.52315853, 0.8196928 , 0.57379612, 0.30507082],
       [0.90080798, 0.23724769, 0.69429896, 0.08561021]])

###`Q-16:` Replace odd elements in arrays with -1.

In [ ]:
#Code here

In [ ]:
mat_odd = np.random.randint(1,101,size=(3,4))
mat_odd

array([[54, 93, 39, 84],
       [49, 19, 76, 51],
       [88, 19, 92, 17]])

In [ ]:
mat_odd[mat_odd%2 != 0]=-1
mat_odd

array([[54, -1, -1, 84],
       [-1, -1, 76, -1],
       [88, -1, 92, -1]])

###`Q-17:` Given two arrays of same shape make an array of max out of two arrays. (Numpy way)
```
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

Result-> [6 3 1 7 8]
```

In [ ]:
#Code here

In [4]:
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])
out_arr = []
for i in range(len(a)):
  if a[i]>=b[i]:
    out_arr.append(a[i])
  else:
    out_arr.append(b[i])



In [5]:
out_arr

[6, 3, 1, 7, 8]

###`Q-18` Answer below asked questions on given array:
1. Fetch Every alternate column of the array
2. Normalise the given array

https://en.wikipedia.org/wiki/Normalization_(statistics)

There are different form of normalisation for this question use below formula.

$$\large X_{normalized} = \frac{X - X_{min}}{X_{max} - X_{min}}$$

```python
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
```


In [6]:
# Given
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
arr1

array([[1568, 7548, 8069, 1006, 6887],
       [8271, 5250, 7052, 6529,  817],
       [2010, 6025,  937,  954, 4554],
       [4730, 3486, 4672, 5201,  205],
       [ 619, 5832, 3782, 4254,  619],
       [5623, 7789, 8118, 4979, 1692],
       [1555, 3828, 5758, 1467, 7407],
       [2613, 9669, 4907, 4300, 9622]])

In [8]:
#Code here
arr1 = arr1-np.min(arr1)/(np.max(arr1)-np.min(arr1))
arr1

array([[1567.97833897, 7547.97833897, 8068.97833897, 1005.97833897,
        6886.97833897],
       [8270.97833897, 5249.97833897, 7051.97833897, 6528.97833897,
         816.97833897],
       [2009.97833897, 6024.97833897,  936.97833897,  953.97833897,
        4553.97833897],
       [4729.97833897, 3485.97833897, 4671.97833897, 5200.97833897,
         204.97833897],
       [ 618.97833897, 5831.97833897, 3781.97833897, 4253.97833897,
         618.97833897],
       [5622.97833897, 7788.97833897, 8117.97833897, 4978.97833897,
        1691.97833897],
       [1554.97833897, 3827.97833897, 5757.97833897, 1466.97833897,
        7406.97833897],
       [2612.97833897, 9668.97833897, 4906.97833897, 4299.97833897,
        9621.97833897]])

###`Q-19:` Write a function which will accept 2 arguments.
First: A 1D numpy array arr

Second: An integer n {Please make sure n<=len(arr)}

Output: The output should be the nth largest item out of the array
```
# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40
```

In [10]:
#Code here
def custom_largn(arr,pos):
  if pos <= len(arr):
    pass
  else:
    print('the postion is larger than the total length of array')
  return np.sort([pos-1])

In [11]:
arr = (12,34,40,7,1,0)
custom_largn(arr,3)

array([2])

###`Q-20:` Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
```
# Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```

In [18]:
#code here
a = np.array([1,2,3])
total_len = len(a)
np.tile(a,total_len)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [19]:
np.repeat(a,total_len)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [20]:
output_arr = np.concatenate((np.repeat(a,total_len),np.tile(a,total_len)))
output_arr

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])